
loadbalancer:
  ports:
  - ${VAMP_UI_PORT}:8080
  tty: true
  image: rancher/load-balancer-service
  links:
  - vamp:vamp
  stdin_open: true

vamp:
  environment:
    VAMP_CONTAINER_DRIVER_RANCHER_URL: ${VAMP_CONTAINER_DRIVER_RANCHER_URL}
    VAMP_CONTAINER_DRIVER_RANCHER_USER: ${VAMP_CONTAINER_DRIVER_RANCHER_USER}
    VAMP_CONTAINER_DRIVER_RANCHER_PASSWORD: ${VAMP_CONTAINER_DRIVER_RANCHER_PASSWORD}
    VAMP_DATABASE_TYPE: ${VAMP_DATABASE_TYPE}
    VAMP_KEY_VALUE_STORE_TYPE: ${VAMP_KEY_VALUE_STORE_TYPE}
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  tty: true
  image: magneticio/vamp:0.9.1-rancher
  stdin_open: true
  links:
  - ${VAMP_KEY_SERVICE}:${VAMP_KEY_VALUE_STORE_TYPE}
  - ${VAMP_DATABASE_SERVICE}:${VAMP_DATABASE_TYPE}

vamp-gateway-agent:
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  tty: true
  command:
  - --storeType=${VAMP_KEY_VALUE_STORE_TYPE}
  - --storeConnection=${VAMP_KEY_VALUE_STORE_TYPE}:${VAMP_KEY_VALUE_STORE_PORT}
  - --storeKey=${VAMP_KEY_VALUE_STORE_KEY}
  - --logstash=${VAMP_DATABASE_TYPE}:${VAMP_DATABASE_PORT}
  image: magneticio/vamp-gateway-agent:0.9.1
  links:
  - ${VAMP_KEY_SERVICE}:${VAMP_KEY_VALUE_STORE_TYPE}
  - ${VAMP_DATABASE_SERVICE}:${VAMP_DATABASE_TYPE}
  stdin_open: true
