.catalog:
  name: "Vamp"
  version: "v0.9.0-rancher"
  description: "Vamp, or the Very Awesome Microservices Platform, takes the pain out of running complex and critical service based architectures. Vamp's core features are a platform-agnostic microservices DSL, powerful A-B testing/canary releasing, autoscaling and an integrated metrics & event engine."
  uuid: vamp-0
  minimum_rancher_version: v0.51.0
  questions:    
    - variable: VAMP_UI_PORT
      description: "public port to access the vamp ui"
      label: "Vamp UI port"
      required: true
      default: "9090"
      type: "int"
    - variable: VAMP_CONTAINER_DRIVER_RANCHER_URL
      description: "Find the API endpoint, e.g. http://192.168.99.100:8080/v1/projects/1a5, using the API button in the top."
      label: "Rancher Server API endpoint"
      required: true
      default: "http://172.17.0.2:8080/v1/projects/1a5"
      type: "string"
    - variable: VAMP_CONTAINER_DRIVER_RANCHER_USER
      description: "Optional Rancher API access key"
      label: "Rancher API access key"
      required: false
      type: "string"
    - variable: VAMP_CONTAINER_DRIVER_RANCHER_PASSWORD
      description: "Optional Rancher API access key secret"
      label: "Rancher API access key secret"
      required: false
      type: "password"

vamp-workflow-health:
  scale: 1
consul:
  scale: 1
vamp-workflow-metrics:
  scale: 1
loadbalancer:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
elastic:
  scale: 1
vamp-workflow-kibana:
  scale: 1
vamp:
  scale: 1